# Generated by Django 6.0.4 on 2026-04-29 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_teamtype_engineeringteam_team_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMeetingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('scheduled_for', models.DateTimeField()),
                ('platform', models.CharField(choices=[('teams', 'Microsoft Teams'), ('zoom', 'Zoom'), ('meet', 'Google Meet'), ('phone', 'Phone call')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_meeting_requests', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_requests', to='core.engineeringteam')),
            ],
            options={
                'ordering': ['scheduled_for', '-created_at'],
            },
        ),
    ]
